### ISSUE TITLE
Migrate away from CRA

### ISSUE THREAD

**Issue by mogusbi-motech** [motech-development/platform#718]
CRA isn't recommended any more. Migrate existing apps to Vite for the time being before evaluating the use of something like Next or Gatsby for the UI refresh

### Accounts
- [x] Serve/build application
- [x] Service worker
- [x] Typechecking
- [x] Linting
- [x] Jest test
- [x] Cypress tests
- [x] Update GH Action

### ID
- [x] Serve/build application
- [x] Typechecking
- [x] Linting
- [x] Jest tests
- [x] Static content generation

### Packages
- [x] Update `eslint` rules for config files
- [x] Add `babel` presets for packages

**Comment by mogusbi-motech** [comment]
## Tasks

### Accounts
- [ ] Serve/build application
- [ ] Service worker
- [ ] Jest test
- [ ] Cypress tests

### ID
- [ ] Serve/build application
- [ ] Jest tests

### Packages
- [ ] Update `eslint` rules for config files
- [ ] Add `babel` presets for packages
